# Generated by Django 4.2.30 on 2026-06-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='matric_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
